kind: Deployment
apiVersion: apps/v1
metadata:
  name: gundnsadmin
  labels:
    app: gundnsadmin
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: gundnsadmin
  template:
    metadata:
      labels:
        app: gundnsadmin
    spec:
      containers:
        - name: gundnsadmin
          image: gundnsadmin/pda-legacy
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: gundnsadmin-env
          imagePullPolicy: Always
      restartPolicy: Always