apiVersion: v1
kind: Service
metadata:
  name: gundnsadmin
  namespace: gundnsadmin
  labels:
    app: gundnsadmin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: gundnsadmin

